services:
  postgres:
    image: postgres:16-alpine
    container_name: realcode
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: bspq26e8-backend:latest
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: realcode-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "10000:10000"

  frontend:
    image: bspq26e8-frontend:latest
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: realcode-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

  performance:
    image: grafana/k6:latest
    container_name: realcode-performance
    restart: "no"
    depends_on:
      - backend
    ports:
      - "6565:6565"
    volumes:
      - ./src/backend/src/test/performance:/scripts #
    command: run /scripts/main.js #



  judge0-db:
    image: postgres:16.2
    container_name: judge-db
    ports:
        - "5433:5432"
    restart: always
    env_file:
      - judge0.conf
    volumes:
      - judge0_data:/var/lib/postgresql/data

  judge0-server:
    image:  judge0/judge0:latest
    depends_on:
      - judge0-db
      - judge0-redis
    container_name: judge0-server
    restart: always
    ports:
        - "2358:2358"
    privileged: true
    volumes:
      - ./judge0.conf:/judge0.conf:ro

  judge0-redis:
    image: redis:7.2.4
    container_name: judge0-redis
    env_file: judge0.conf
    restart: always
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"']

  judge0-worker:
    image: judge0/judge0:latest
    container_name: judge0-worker
    restart: always
    depends_on:
      - judge0-db
      - judge0-redis
    volumes:
      - ./judge0.conf:/judge.conf:ro
    privileged: true
    command: ["./scripts/workers"]

volumes:
  postgres_data:
  judge0_data:





