spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:app_db}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:BSPQ26E8}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:skillissue}}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:mySecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}
